CREATE TABLE vets (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
  first_name VARCHAR2(30),
  last_name VARCHAR2(30)
);

CREATE INDEX idx_vets ON vets (last_name);

CREATE TABLE specialties (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR2(80)
);

CREATE INDEX idx_specialties ON specialties (name);

CREATE TABLE vet_specialties (
  vet_id NUMBER NOT NULL,
  specialty_id NUMBER NOT NULL
);

ALTER TABLE vet_specialties ADD CONSTRAINT FK_vet_specialties_vets FOREIGN KEY (vet_id) REFERENCES vets(id);
CREATE INDEX idx_vet_specialties_fk1 ON vet_specialties (vet_id);

ALTER TABLE vet_specialties ADD CONSTRAINT FK_vet_specialties_specialties FOREIGN KEY (specialty_id) REFERENCES specialties(id);
CREATE INDEX idx_vet_specialties_fk2 ON vet_specialties (specialty_id);

CREATE UNIQUE INDEX udx_vet_specialties ON vet_specialties (vet_id,specialty_id);

CREATE TABLE types (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR2(80)
);

CREATE INDEX idx_types ON types (name);

CREATE TABLE owners (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
  first_name VARCHAR2(30),
  last_name VARCHAR2(30),
  address VARCHAR2(255),
  city VARCHAR2(80),
  telephone VARCHAR2(20)
);

CREATE INDEX idx_owners ON owners (last_name);

CREATE TABLE pets (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR2(30),
  birth_date DATE,
  type_id NUMBER NOT NULL,
  owner_id NUMBER NOT NULL
);

ALTER TABLE pets ADD CONSTRAINT FK_pets_owners FOREIGN KEY (owner_id) REFERENCES owners(id);
CREATE INDEX idx_pets_fk1 ON pets (owner_id);

ALTER TABLE pets ADD CONSTRAINT FK_pets_types FOREIGN KEY (type_id) REFERENCES types(id);
CREATE INDEX idx_pets_fk2 ON pets (type_id);

CREATE INDEX idx_pets ON pets (name);

CREATE TABLE visits (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
  pet_id NUMBER NOT NULL,
  visit_date DATE,
  description VARCHAR2(255)
);

ALTER TABLE visits ADD CONSTRAINT FK_visits_pets FOREIGN KEY (pet_id) REFERENCES pets(id);
CREATE INDEX idx_visits_fk1 ON visits (pet_id);
