Success! [1mOverrided[0m <name> with [1m<override>[0m at <path>
Inside that directory, you can run several commands:

  npm install
    Installs all the dependencies.

  npm start
    Starts the development server.

  npm run build
    Bundles the app into static files for production.

  npm test
    Starts the test runner.

  npm run eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  [1m<executable> -loadjson[0m
  [1mcd <name>[0m
  [1mnpm install[0m
  [1mnpm start[0m

Happy hacking!
