Success! Created <name> at <path>
Inside that directory, you can run several commands:

  npm install -g @oracle/ojet-cli
    Installs the Oracle Jet CLI.

  ojet restore
    Installs all the needed dependencies.

  ojet serve web
    Starts the development server.
<envRequirement>
We suggest that you begin by typing:

  [1mcd <name>[0m
  [1mnpm install -g @oracle/ojet-cli[0m
  [1mojet restore[0m
  [1mojet serve web[0m

Happy hacking!
